### PR TITLE
Allow options to be passed to ssh with -o

### PR DESCRIPTION
**Pull request by mingaldrichgan**

### CODE REVIEW

**Comment by sepich** [comment]
Thanks, but could you please describe your User Story?
 - why this cannot be configured in `.ssh/config`?
 - what about multiple `-o` arguments, shouldn't here be `action='append'` in argparse?

**Comment by mingaldrichgan** [comment]
1. This allows you to override the `.ssh/config` settings in specific circumstances. I personally have a use case for this but if you don't think it's a common enough need, feel free to reject this PR.
2. Good call. **If** you decide to proceed with this PR, I will make the change. Please let me know.

Thanks!

**Comment by sepich** [comment]
No offence, i'm just curious how do people use it. As i'm not usually call i2cssh.py manually from command line.
If you think this could be useful for others - let's do `-o` similar to `ssh` to avoid WTFs. Also, let's add a note to Readme, that options only work in `Key=Value` style and not `"Key Value"`.

**Comment by mingaldrichgan** [comment]
I decided to close this PR for now. Thank you for this, by the way! The original `i2cssh` was frustrating.

**Pull request closed without merging**
